      
      COMMON /COGRDOLD/
     &                 KMXOLD,  JMXOLD,  IMXOLD,
     &                 LEVELOLD,    LCHILDOLD, IPARENTOLD,
     &                 IPOSOLD, JPOSOLD, KPOSOLD,
     &                 XMINOLD,    YMINOLD,    ZMINOLD,
     &                 XTOTOLD,     YTOTOLD,     ZTOTOLD,   
     &                 NBOCOLD,
     &                 FRONTOLD,    BACKOLD,     RIGHTOLD,     LEFTOLD,
     &                 BOTTOMOLD,   TOPOLD,      CUBEOLD,
     &                 IFRNBROLD, IBANBROLD, IRINBROLD, ILENBROLD,
     &                 IBONBROLD, ITONBROLD,
     &                 IBPOSOLD,   JBPOSOLD,    KBPOSOLD,
     &                 IBANFOLD,  IBENDOLD,
     &                 JBANFOLD,  JBENDOLD,
     &                 KBANFOLD,  KBENDOLD,
     &                 XHOMOGOLD,   YHOMOGOLD,   ZHOMOGOLD,
     &                 LPLEVELOLD

      INTEGER
     &       KMXOLD(MAXGRIDS), JMXOLD(MAXGRIDS), IMXOLD(MAXGRIDS),
     &       LEVELOLD(MAXGRIDS), 
     &       IPARENTOLD(MAXGRIDS),
     & IPOSOLD(MAXGRIDS), JPOSOLD(MAXGRIDS), KPOSOLD(MAXGRIDS),

     &  NBOCOLD(7,MAXGRIDS),
     &  IFRNBROLD(MAXBOCONDS,MAXGRIDS), IBANBROLD(MAXBOCONDS,MAXGRIDS),
     &  IRINBROLD(MAXBOCONDS,MAXGRIDS), ILENBROLD(MAXBOCONDS,MAXGRIDS),
     &  IBONBROLD(MAXBOCONDS,MAXGRIDS), ITONBROLD(MAXBOCONDS,MAXGRIDS),
     &  IBPOSOLD(MAXBOCONDS,7,MAXGRIDS),JBPOSOLD(MAXBOCONDS,7,MAXGRIDS),
     &  KBPOSOLD(MAXBOCONDS,7,MAXGRIDS),
     &  IBANFOLD(MAXBOCONDS,7,MAXGRIDS),IBENDOLD(MAXBOCONDS,7,MAXGRIDS),
     &  JBANFOLD(MAXBOCONDS,7,MAXGRIDS),JBENDOLD(MAXBOCONDS,7,MAXGRIDS),
     &  KBANFOLD(MAXBOCONDS,7,MAXGRIDS),KBENDOLD(MAXBOCONDS,7,MAXGRIDS)


      REAL
     &       XTOTOLD(MAXGRIDS), YTOTOLD(MAXGRIDS), ZTOTOLD(MAXGRIDS),
     &       XMINOLD(MAXGRIDS), YMINOLD(MAXGRIDS), ZMINOLD(MAXGRIDS)

      CHARACTER (LEN=16)
     &   FRONTOLD(MAXBOCONDS,MAXGRIDS),   BACKOLD(MAXBOCONDS,MAXGRIDS),
     &   RIGHTOLD(MAXBOCONDS,MAXGRIDS),   LEFTOLD(MAXBOCONDS,MAXGRIDS),
     &  BOTTOMOLD(MAXBOCONDS,MAXGRIDS),    TOPOLD(MAXBOCONDS,MAXGRIDS),
     &    CUBEOLD(MAXBOCONDS,MAXGRIDS)

      LOGICAL
     &      LCHILDOLD(MAXGRIDS),
     &  XHOMOGOLD(MAXGRIDS), YHOMOGOLD(MAXGRIDS), ZHOMOGOLD(MAXGRIDS),
     &      LPLEVELOLD(MAXGRIDS)
