      PARAMETER (MAXTHREADS = 60)
      COMMON /TEAMID/ ITEAM 
      COMMON /THREADID/ ITHREAD 
C*KSR* PSC   /THREADID/
      COMMON /COIDTHR/ IDTHROFGRD,NVPOFTHR,IVPOFTHR,NTSOFTHR,ITSOFTHR
      INTEGER IDTHROFGRD(MAXGRIDS),
     $        IVPOFTHR  (MAXGRDSOFLVL,MAXTHREADS,MINLVLMIN:MAXLVLMAX),
     $        NVPOFTHR  (             MAXTHREADS,MINLVLMIN:MAXLVLMAX),
     $        ITSOFTHR  (MAXGRDSOFLVL,MAXTHREADS,MINLVLMIN:MAXLVLMAX),
     $        NTSOFTHR  (             MAXTHREADS,MINLVLMIN:MAXLVLMAX)

