
     $ KK,JJ,II,KKA,JJA,IIA,KMX,JMX,IMX,KMXA,JMXA,IMXA,NBND,
     $ ISELEA,ISELEP,
     $ ISAMPA,ISAMPP,ISLINP,ISLINA,ISLIDI,
     $ RIDENT,HILF,B,U,UO,AU,SU,UFG,AURG,SURG,AUSKG,SUSKG,AUFLG,SUFLG,V,
     $ VO,AV,SV,VFG,AVRG,SVRG,AVSKG,SVSKG,AVFLG,SVFLG,W,WO,AW,SW,WFG,
     $ AWRG,SWRG,AWSKG,SWSKG,AWFLG,SWFLG,P,AP,SP,PFG,APRG,SPRG,
     $ APSKG,SPSKG,APFLG,SPFLG,
     $ G,AEFG,SEFG,AEFS,SEFS,ADFG,SDFG,
     $ ADUDX2,SDUDX2,ADUDY2,SDUDY2,ADUDZ2,SDUDZ2,ADVDX2,SDVDX2,ADVDY2,
     $ SDVDY2,ADVDZ2,SDVDZ2,ADWDX2,SDWDX2,ADWDY2,SDWDY2,ADWDZ2,SDWDZ2,
     $ AUFWFG,SUFWFG,AUFWFS,SUFWFS,AUFWFM,SUFWFM,AVFWFG,SVFWFG,AVFWFS,
     $ SVFWFS,AVFWFM,SVFWFM,AUFVFG,SUFVFG,AUFVFS,SUFVFS,AUFVFM,
     $ SUFVFM,OX,AOX,SOX,OXFG,AOXRG,SOXRG,OY,AOY,SOY,OYFG,
     $ AOYRG,SOYRG,OZ,AOZ,SOZ,OZFG,AOZRG,SOZRG,AO2,SO2,O2FG,AO2RG,
     $ SO2RG,AHE,SHE,HEFG,AHERG,SHERG
#ifdef _TAU_NN_
     $ ,TAU11,TAU12,TAU13,TAU21,TAU22,TAU23,TAU31,TAU32,TAU33,
     $ ATAU11,STAU11,ATAU12,STAU12,ATAU13,STAU13,ATAU22,STAU22,
     $ ATAU23,STAU23,ATAU33,STAU33
#endif
#ifdef _FRED_BODY_
     $ ,BP,BU,BV,BW
#endif
#ifdef _TSCAL_
     $ ,T,TO,AT,ST,TFG,ATRG,STRG,
     $ ATSKG,STSKG,ATFLG,STFLG,
     $ AUFTFG,SUFTFG,AUFTFS,SUFTFS,AUFTFM,SUFTFM,
     $ AVFTFG,SVFTFG,AVFTFS,SVFTFS,AVFTFM,SVFTFM,
     $ AWFTFG,SWFTFG,AWFTFS,SWFTFS,AWFTFM,SWFTFM
#endif
#if (defined _NEWSTAT_)
     $ ,HILF3D1,HILF3D2,HILF3D3
#endif
#if (defined _STAT11_)
     $ ,AUUM,SUUM,AVVM,SVVM,AWWM,SWWM,APPM,SPPM
#endif
#if (defined _STAT12_)
     $ ,AUVM,SUVM,AUWM,SUWM,AVWM,SVWM
#endif
#if (defined _STAT13_)
     $ ,AUXUXM,SUXUXM,AUYUYM,SUYUYM,AUZUZM,SUZUZM,AVXVXM,SVXVXM,AVYVYM
     $ ,SVYVYM,AVZVZM,SVZVZM,AWXWXM,SWXWXM,AWYWYM,SWYWYM,AWZWZM,SWZWZM
#endif
#if (defined _STAT14_)
     $ ,AUUUM,SUUUM,AVVVM,SVVVM,AWWWM,SWWWM,AUUVM,SUUVM,AUUWM,SUUWM
     $ ,AVVUM,SVVUM,AVVWM,SVVWM,AWWUM,SWWUM,AWWVM,SWWVM,AUVWM,SUVWM
     $ ,AUPM,SUPM,AVPM,SVPM,AWPM,SWPM
     $ ,AUXPM,SUXPM,AVYPM,SVYPM,AWZPM,SWZPM
     $ ,AUYVXP,SUYVXP,AUZWXP,SUZWXP,AVZWYP,SVZWYP,AUXVXM,SUXVXM
     $ ,AUYVYM,SUYVYM,AUZVZM,SUZVZM,AUXWXM,SUXWXM,AUYWYM,SUYWYM
     $ ,AUZWZM,SUZWZM,AVXWXM,SVXWXM,AVYWYM,SVYWYM,AVZWZM,SVZWZM
#endif
#if (defined _STAT15_)
     $ ,AUTM,SUTM,AVTM,SVTM,AWTM,SWTM,ATTM,STTM,ASSM,SSSM
#endif
#if (defined _STAT17_)
     $ ,AUTTM,SUTTM,AVTTM,SVTTM,AWTTM,SWTTM
     $ ,ATXTXM,STXTXM,ATYTYM,STYTYM,ATZTZM,STZTZM
#endif
#if (defined _STAT20_)
     $ ,AUUUUM,SUUUUM,AVVVVM,SVVVVM,AWWWWM,SWWWWM,APPPPM,SPPPPM
#ifdef _TSCAL_
     $ ,ATTTTM,STTTTM,ATTTM,STTTM
#endif
#endif
     $ )
