
     $ KK,JJ,II,KKA,JJA,IIA,KK,JJ,II,KKA,JJA,IIA,NBND,ISELEA,ISELEP,
     $ ISAMPA(1,IGRID),ISAMPP(1,IGRID),ISLINP,ISLINA,ISLIDI,RIDENT,
     $   HILF(IP3),     B(IP3),     U(IP3),    UO(IP3),    AU(IAV),
     $     SU(IAV),   UFG(IP3),  AURG(IAV),  SURG(IAV), AUSKG(IAV),
     $  SUSKG(IAV), AUFLG(IAV), SUFLG(IAV),     V(IP3),    VO(IP3),
     $     AV(IAV),    SV(IAV),   VFG(IP3),  AVRG(IAV),  SVRG(IAV),
     $  AVSKG(IAV), SVSKG(IAV), AVFLG(IAV), SVFLG(IAV),     W(IP3),
     $     WO(IP3),    AW(IAV),    SW(IAV),   WFG(IP3),  AWRG(IAV),
     $   SWRG(IAV), AWSKG(IAV), SWSKG(IAV), AWFLG(IAV), SWFLG(IAV),
     $      P(IP3),    AP(IAV),    SP(IAV),   PFG(IP3),  APRG(IAV),
     $   SPRG(IAV), APSKG(IAV), SPSKG(IAV), APFLG(IAV), SPFLG(IAV),
     $      G(IP3),  AEFG(IAV),  SEFG(IAV),  AEFS(IAV),  SEFS(IAV),      
     $   ADFG(IAV),  SDFG(IAV),        
     $ ADUDX2(IAV),SDUDX2(IAV),ADUDY2(IAV),
     $ SDUDY2(IAV),ADUDZ2(IAV),SDUDZ2(IAV),ADVDX2(IAV),SDVDX2(IAV),
     $ ADVDY2(IAV),SDVDY2(IAV),ADVDZ2(IAV),SDVDZ2(IAV),ADWDX2(IAV),
     $ SDWDX2(IAV),ADWDY2(IAV),SDWDY2(IAV),ADWDZ2(IAV),SDWDZ2(IAV),
     $ AUFWFG(IAV),SUFWFG(IAV),AUFWFS(IAV),SUFWFS(IAV),AUFWFM(IAV),
     $ SUFWFM(IAV),AVFWFG(IAV),SVFWFG(IAV),AVFWFS(IAV),SVFWFS(IAV),
     $ AVFWFM(IAV),SVFWFM(IAV),AUFVFG(IAV),SUFVFG(IAV),AUFVFS(IAV),
     $ SUFVFS(IAV),AUFVFM(IAV),SUFVFM(IAV),    OX(IP3),   AOX(IAV),
     $    SOX(IAV),  OXFG(IP3), AOXRG(IAV), SOXRG(IAV),    OY(IP3),
     $    AOY(IAV),   SOY(IAV),  OYFG(IP3), AOYRG(IAV), SOYRG(IAV),
     $     OZ(IP3),   AOZ(IAV),   SOZ(IAV),  OZFG(IP3), AOZRG(IAV),
     $  SOZRG(IAV),   AO2(IAV),   SO2(IAV),  O2FG(IP3), AO2RG(IAV),
     $  SO2RG(IAV),   AHE(IAV),   SHE(IAV),  HEFG(IP3), AHERG(IAV),
     $  SHERG(IAV)
#ifdef _TAU_NN_
     $ ,TAU11(IP3), TAU12(IP3), TAU13(IP3), TAU21(IP3), TAU22(IP3),
     $  TAU23(IP3), TAU31(IP3), TAU32(IP3), TAU33(IP3),
     $ ATAU11(IAV), STAU11(IAV), ATAU12(IAV), STAU12(IAV),
     $ ATAU13(IAV), STAU13(IAV), ATAU22(IAV), STAU22(IAV),
     $ ATAU23(IAV), STAU23(IAV), ATAU33(IAV), STAU33(IAV)
#endif
#ifdef _FRED_BODY_
     $   ,BP(IP3),     BU(IP3),     BV(IP3),     BW(IP3)
#endif
#ifdef _TSCAL_
     $   ,T(IP3), TO(IP3), AT(IAV), ST(IAV), TFG(IP3), ATRG(IAV),
     $   STRG(IAV), 
     $  ATSKG(IAV), STSKG(IAV), ATFLG(IAV), STFLG(IAV),     
     $ AUFTFG(IAV),SUFTFG(IAV),AUFTFS(IAV),SUFTFS(IAV),AUFTFM(IAV),
     $ SUFTFM(IAV),
     $ AVFTFG(IAV),SVFTFG(IAV),AVFTFS(IAV),SVFTFS(IAV),AVFTFM(IAV),
     $ SVFTFM(IAV),
     $ AWFTFG(IAV),SWFTFG(IAV),AWFTFS(IAV),SWFTFS(IAV),AWFTFM(IAV),
     $ SWFTFM(IAV)  
#endif
#if (defined _NEWSTAT_)
     $ ,HILF3D1(IP3),HILF3D2(IP3),HILF3D3(IP3)
#endif
#if defined _STAT11_
     $ ,AUUM(IAV),SUUM(IAV),AVVM(IAV),SVVM(IAV),AWWM(IAV),SWWM(IAV)
     $ ,APPM(IAV),SPPM(IAV)
#endif
#if defined _STAT12_
     $ ,AUVM(IAV),SUVM(IAV),AUWM(IAV),SUWM(IAV),AVWM(IAV),SVWM(IAV)
#endif
#if defined _STAT13_
     $ ,AUXUXM(IAV),SUXUXM(IAV),AUYUYM(IAV),SUYUYM(IAV)
     $ ,AUZUZM(IAV),SUZUZM(IAV),AVXVXM(IAV),SVXVXM(IAV)
     $ ,AVYVYM(IAV),SVYVYM(IAV),AVZVZM(IAV),SVZVZM(IAV)
     $ ,AWXWXM(IAV),SWXWXM(IAV),AWYWYM(IAV),SWYWYM(IAV)
     $ ,AWZWZM(IAV),SWZWZM(IAV)
#endif
#if defined _STAT14_
     $ ,AUUUM(IAV), SUUUM(IAV), AVVVM(IAV), SVVVM(IAV)
     $ ,AWWWM(IAV), SWWWM(IAV), AUUVM(IAV), SUUVM(IAV)
     $ ,AUUWM(IAV), SUUWM(IAV), AVVUM(IAV), SVVUM(IAV)
     $ ,AVVWM(IAV), SVVWM(IAV), AWWUM(IAV), SWWUM(IAV)
     $ ,AWWVM(IAV), SWWVM(IAV), AUVWM(IAV), SUVWM(IAV)
     $ ,AUPM(IAV),  SUPM(IAV),  AVPM(IAV),  SVPM(IAV)
     $ ,AWPM(IAV),  SWPM(IAV),  AUXPM(IAV), SUXPM(IAV)
     $ ,AVYPM(IAV), SVYPM(IAV), AWZPM(IAV), SWZPM(IAV)
     $ ,AUYVXP(IAV),SUYVXP(IAV),AUZWXP(IAV),SUZWXP(IAV)
     $ ,AVZWYP(IAV),SVZWYP(IAV),AUXVXM(IAV),SUXVXM(IAV)
     $ ,AUYVYM(IAV),SUYVYM(IAV),AUZVZM(IAV),SUZVZM(IAV)
     $ ,AUXWXM(IAV),SUXWXM(IAV),AUYWYM(IAV),SUYWYM(IAV)
     $ ,AUZWZM(IAV),SUZWZM(IAV),AVXWXM(IAV),SVXWXM(IAV)
     $ ,AVYWYM(IAV),SVYWYM(IAV),AVZWZM(IAV),SVZWZM(IAV)
#endif
#if (defined _STAT15_)
     $ ,AUTM(IAV),SUTM(IAV),AVTM(IAV),SVTM(IAV),AWTM(IAV)
     $ ,SWTM(IAV),ATTM(IAV),STTM(IAV),ASSM(IAV),SSSM(IAV)
#endif
#if (defined _STAT17_)
     $ ,AUTTM(IAV),SUTTM(IAV),AVTTM(IAV)
     $ ,SVTTM(IAV),AWTTM(IAV),SWTTM(IAV)
     $ ,ATXTXM(IAV),STXTXM(IAV),ATYTYM(IAV)
     $ ,STYTYM(IAV),ATZTZM(IAV),STZTZM(IAV)
#endif

#if (defined _STAT20_)
     $ ,AUUUUM(IAV),SUUUUM(IAV),AVVVVM(IAV),SVVVVM(IAV)
     $ ,AWWWWM(IAV),SWWWWM(IAV),APPPPM(IAV),SPPPPM(IAV)
#ifdef _TSCAL_
     $ ,ATTTTM(IAV),STTTTM(IAV),ATTTM(IAV),STTTM(IAV)
#endif
#endif
     $ )
