










CCCCC        DEFINITIONEN FUER C-PREPROZESSOR
C            MASCHINE

C              MESSAGE PASSING INTERFACE

C            RAEUMLICHE DISKRETISIERUNG
C
***********************************************************************
C                       KOMPAKT-UPWIND in X-RICHTUNG (3-TER ORDNUNG) fuer
C                       die U-Komponente (V und W bleiben Kompakt 4ter ordnung)
C                       falls im Stroemungsfeld eine Koerper vorhanden ist
C
***********************************************************************
C                       KOMPAKTVERF. in XYZ-RICHTUNG (4-TER ORDNUNG)


**********************************************************************
C                      Preprocessing with ADM for 2nd Order Central
***********************************************************************
CCC                     Bei periodischen Randbedingungen in X-Richtung
CCC                     ist eine hoehere O
C
CCC                     Bei periodischen Randbedingungen in Y-Richtung
CCC                     ist eine hoehere Ordnung moeglich
C
CCC                     Bei periodischen Randbedingungen in Y-Richtung:
CCC                     Zentraldiff. 4-ter Ordnung (Parallelisieung moeglich)
C
***********************************************************************
C
C
C            INTERPOLATION AN GITTER-GRENZEN

C            BEHANDLUNG DER TOPAR-RANDBEDINGUNG

C            ZEITLICHE DISKRETISIERUNG

C            FEINSTRUKTURMODELL

C            NICHT-NEWTONSCHE SPANNUNGEN


C            TRANSPORT UND ORIENTIERUNG VON PARTIKELN


C            SCALAR HEAT/TEMPERATURE TRANSPORT
C            APROXIMATE DECONVOLUTION FOR SCALAR
C            TURBULENT PRANDTL NUMBER 
C            PLOT LOCAL SCALAR CONVECTION DIFFUSION EXTREMES 
C            ANALYZE AND PLOT NEAR WALL GRID RESLOLUTION 
C            WRITE SPECIAL 1D LINE FOR TMIX FOR SPECTRA AND PDF
C            SCALAR TIME ADVANCEMENT/DISCRETISATION METHOD

C            STROEMUNG NACH OBEN?


C            BEHANDLUNG DER FLUKTUATIONS-RANDBEDINGUNG

C            BEHANDLUNG VON PPHYS ALS QUELLTERM IN TSTLE2

C            POSITIONIERUNG DER EINSTROEMPROFILE

C           STATISTIK


C                 GEMISCHTES

C                GRDFMI WIRD NICHT VERWENDET, DAHER EINSPARUNG DER FELDER
C                IGRHF UND GRHF

C                VERGROESSERN DER KJI-RICHTUNG BEI FORTSETZUNGSLAUF ERLAUBT!

C                RAUSSCHREIBEN VON ZEITRECORDS

C                FUER KORRELATIONEN UND HAEFIGKEITSVERTEILUNGEN
      SUBROUTINE DIBHEAD (CIDENT,IIDENT,RIDENT,
     $                    ISELEA,ISAMPA,ISLINA,ISLIDI)
CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C          LIEST HEADERINFORMATION VON ERGEBNISFILE EIN
C          BINAER
C
C
C     16. 5.93 (MM) : ORIGINAL
C     26. 5.95 (MM) : MPI EINGEFUEHRT
C
CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C


      INTEGER MAXGRIDS,MAXBOCONDS
      PARAMETER ( MAXGRIDS         =128 )
      PARAMETER ( MAXBOCONDS       = 10 )


      COMMON /COMGRID/
     &               NGRID,    NGRDOLD,   NGRDSET, NGRDDFD,
     &               NAUFP,    NAUFOLD,
     &                 KMX,  JMX,  IMX,
     &                 KMXA, JMXA, IMXA,
     &                IP3D, IP2D, IP1D, IPBB,IPB3, IPBU,
     &                NOF3D,NOF2D,NOF1D,NOFBB,NOFB3,NOFBU,
     &                IPA,   IP1L,  IP2L,
     &                NOFA,  NOF1L, NOF2L,  
     &                 IC1,  IC2,  JC1,  JC2,  KC1,  KC2

      INTEGER
     &         KMX(MAXGRIDS),     JMX(MAXGRIDS),       IMX(MAXGRIDS),
     &        KMXA(MAXGRIDS),    JMXA(MAXGRIDS),      IMXA(MAXGRIDS),
     &        IP3D(MAXGRIDS),    IP2D(MAXGRIDS),      IP1D(MAXGRIDS),
     &        IPBB(MAXGRIDS),    IPB3(MAXGRIDS),      IPBU(MAXGRIDS),
     &        NOF3D,   NOF2D,   NOF1D,    NOFBB,   NOFBU,
     &         IPA(MAXGRIDS),    IP1L(MAXGRIDS),      IP2L(MAXGRIDS),
     &         NOFA,   NOF1L,   NOF2L,    NAUFP,
     &         IC1(MAXGRIDS),     IC2(MAXGRIDS),
     &         JC1(MAXGRIDS),     JC2(MAXGRIDS),
     &         KC1(MAXGRIDS),     KC2(MAXGRIDS)
 


      COMMON /COSTRLES/
     $                  VERS,   NRRUN,
     $                  DREAD,  DWRITE, DCONT,  DCUB,   
     $                  LBODYINSERT,
     $                  LGRIDNEW,    LGRIDREMOVE,
     $                  NPRNEU, FPRNEU, MTSTEP,
     $                  DT,     ITPRIN, IPINF,  ITINT,
     $                  IPRINT_WSS, IPRINT_WNS, ITFLUC, ITMIT,  
     $                  MPCORR, EPCORR, EPFAK,  MPCVOR, MPCNACH,
     $                  IVPINF, 
     $                  OMG,    LDIMLO, ISETRE,
     $                  LINPRN, IWRB,   LREC

      INTEGER 
     $                  NRRUN,
     $                  MTURB,  NPRNEU, MTSTEP,
     $                          ITPRIN, IPINF,  ITINT,
     $                  ITFLUC, ITMIT,  MPCORR,        
     $                                          ISETRE,
     $                          MSLIN,  IWRB          

      LOGICAL
     $                  DREAD,  DWRITE, DCONT,  DCUB,   
     $                  LBODYINSERT,
     $                  LGRIDNEW,       LGRIDREMOVE,
     $                  LDIMLO, LINPRN, LREC

      REAL
     $                  DT,     EPCORR,  OMG, FPRNEU

      CHARACTER (LEN=8)       VERS

      
      COMMON /COGRDOLD/
     &                 KMXOLD,  JMXOLD,  IMXOLD,
     &                 LEVELOLD,    LCHILDOLD, IPARENTOLD,
     &                 IPOSOLD, JPOSOLD, KPOSOLD,
     &                 XMINOLD,    YMINOLD,    ZMINOLD,
     &                 XTOTOLD,     YTOTOLD,     ZTOTOLD,   
     &                 NBOCOLD,
     &                 FRONTOLD,    BACKOLD,     RIGHTOLD,     LEFTOLD,
     &                 BOTTOMOLD,   TOPOLD,      CUBEOLD,
     &                 IFRNBROLD, IBANBROLD, IRINBROLD, ILENBROLD,
     &                 IBONBROLD, ITONBROLD,
     &                 IBPOSOLD,   JBPOSOLD,    KBPOSOLD,
     &                 IBANFOLD,  IBENDOLD,
     &                 JBANFOLD,  JBENDOLD,
     &                 KBANFOLD,  KBENDOLD,
     &                 XHOMOGOLD,   YHOMOGOLD,   ZHOMOGOLD,
     &                 LPLEVELOLD

      INTEGER
     &       KMXOLD(MAXGRIDS), JMXOLD(MAXGRIDS), IMXOLD(MAXGRIDS),
     &       LEVELOLD(MAXGRIDS), 
     &       IPARENTOLD(MAXGRIDS),
     & IPOSOLD(MAXGRIDS), JPOSOLD(MAXGRIDS), KPOSOLD(MAXGRIDS),

     &  NBOCOLD(7,MAXGRIDS),
     &  IFRNBROLD(MAXBOCONDS,MAXGRIDS), IBANBROLD(MAXBOCONDS,MAXGRIDS),
     &  IRINBROLD(MAXBOCONDS,MAXGRIDS), ILENBROLD(MAXBOCONDS,MAXGRIDS),
     &  IBONBROLD(MAXBOCONDS,MAXGRIDS), ITONBROLD(MAXBOCONDS,MAXGRIDS),
     &  IBPOSOLD(MAXBOCONDS,7,MAXGRIDS),JBPOSOLD(MAXBOCONDS,7,MAXGRIDS),
     &  KBPOSOLD(MAXBOCONDS,7,MAXGRIDS),
     &  IBANFOLD(MAXBOCONDS,7,MAXGRIDS),IBENDOLD(MAXBOCONDS,7,MAXGRIDS),
     &  JBANFOLD(MAXBOCONDS,7,MAXGRIDS),JBENDOLD(MAXBOCONDS,7,MAXGRIDS),
     &  KBANFOLD(MAXBOCONDS,7,MAXGRIDS),KBENDOLD(MAXBOCONDS,7,MAXGRIDS)


      REAL
     &       XTOTOLD(MAXGRIDS), YTOTOLD(MAXGRIDS), ZTOTOLD(MAXGRIDS),
     &       XMINOLD(MAXGRIDS), YMINOLD(MAXGRIDS), ZMINOLD(MAXGRIDS)

      CHARACTER (LEN=16)
     &   FRONTOLD(MAXBOCONDS,MAXGRIDS),   BACKOLD(MAXBOCONDS,MAXGRIDS),
     &   RIGHTOLD(MAXBOCONDS,MAXGRIDS),   LEFTOLD(MAXBOCONDS,MAXGRIDS),
     &  BOTTOMOLD(MAXBOCONDS,MAXGRIDS),    TOPOLD(MAXBOCONDS,MAXGRIDS),
     &    CUBEOLD(MAXBOCONDS,MAXGRIDS)

      LOGICAL
     &      LCHILDOLD(MAXGRIDS),
     &  XHOMOGOLD(MAXGRIDS), YHOMOGOLD(MAXGRIDS), ZHOMOGOLD(MAXGRIDS),
     &      LPLEVELOLD(MAXGRIDS)

      PARAMETER (NMBODOLD = 100)
      
      COMMON /COBODYOLD/
     &               NBODOLD,  CTYPO,
     &               IB1O,   IB2O,   JB1O,   JB2O,   KB1O,   KB2O,
     &               XB1O,   XB2O,   YB1O,   YB2O,   ZB1O,   ZB2O,
     &               NCOUNO, XMITO,  HEIGHTO, ALPHAO, CDIRO

      INTEGER
     &       NBODOLD,
     &       IB1O(NMBODOLD),   IB2O(NMBODOLD),
     &       JB1O(NMBODOLD),   JB2O(NMBODOLD),
     &       KB1O(NMBODOLD),   KB2O(NMBODOLD),
     &       NCOUNO(NMBODOLD) 

      REAL
     &       XB1O(NMBODOLD),   XB2O(NMBODOLD),
     &       YB1O(NMBODOLD),   YB2O(NMBODOLD),
     &       ZB1O(NMBODOLD),   ZB2O(NMBODOLD),
     &      XMITO(NMBODOLD),HEIGHTO(NMBODOLD),ALPHAO(NMBODOLD)

      CHARACTER (LEN=16) CTYPO(NMBODOLD),CDIRO(NMBODOLD)
 

      CHARACTER (LEN=8) CIDENT(10)
      INTEGER     IIDENT(100)
      REAL        RIDENT(100)

      INTEGER     ISELEA(2*752)    ,ISLINA(ISLIDI),
     $            ISAMPA(752*MAXGRIDS)
CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C
      
      READ(1,END=10000) CIDENT
        READ(1,END=10001) IIDENT

      READ(1,END=10002) RIDENT
C
CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC   MLET ODER MGLET ??
      IF (IIDENT(5).GT.8) THEN
C                                                    HIER: MGLET	
         READ(1,END=10003) NGRDOLD,NBODOLD,NAUFOLD
      DO I=1,NGRDOLD
         READ(1,END=10004)   IMXOLD(I),   JMXOLD(I),    KMXOLD(I)
         READ(1,END=10007) LEVELOLD(I),LCHILDOLD(I),IPARENTOLD(I)
         READ(1,END=10010)  IPOSOLD(I),  JPOSOLD(I),   KPOSOLD(I)
         READ(1,END=10013)  XTOTOLD(I),  YTOTOLD(I),   ZTOTOLD(I)

         IF (IIDENT(5).GE.34) THEN

            READ(1,END=10015) (NBOCOLD(J,I),J=1,7)

            READ(1,END=10016) ( FRONTOLD(J,I),J=1, NBOCOLD(1,I))
            READ(1,END=10016) (  BACKOLD(J,I),J=1, NBOCOLD(2,I))
            READ(1,END=10016) ( RIGHTOLD(J,I),J=1, NBOCOLD(3,I))
            READ(1,END=10016) (  LEFTOLD(J,I),J=1, NBOCOLD(4,I))
            READ(1,END=10016) (BOTTOMOLD(J,I),J=1, NBOCOLD(5,I))
            READ(1,END=10016) (   TOPOLD(J,I),J=1, NBOCOLD(6,I))
            READ(1,END=10016) (  CUBEOLD(J,I),J=1, NBOCOLD(7,I))

            READ(1,END=10017)
            READ(1,END=10017)
            READ(1,END=10017)
            READ(1,END=10017)
            READ(1,END=10017)
            READ(1,END=10017)

C           READ(1,END=10017) (IFRNBROLD(J,I),J=1, NBOCOLD(1,I))
C           READ(1,END=10017) (IBANBROLD(J,I),J=1, NBOCOLD(2,I))
C           READ(1,END=10017) (IRINBROLD(J,I),J=1, NBOCOLD(3,I))
C           READ(1,END=10017) (ILENBROLD(J,I),J=1, NBOCOLD(4,I))
C           READ(1,END=10017) (IBONBROLD(J,I),J=1, NBOCOLD(5,I))
C           READ(1,END=10017) (IBONBROLD(J,I),J=1, NBOCOLD(6,I))

            DO ID = 1,7
              READ(1,END=10017)
              READ(1,END=10017)
              READ(1,END=10017)
              READ(1,END=10017)
              READ(1,END=10017)
              READ(1,END=10017)
              READ(1,END=10017)
              READ(1,END=10017)
              READ(1,END=10017)

C             READ(1,END=10017) (IBPOSOLD(J,ID,I),J=1, NBOCOLD(ID,I))
C             READ(1,END=10017) (JBPOSOLD(J,ID,I),J=1, NBOCOLD(ID,I))
C             READ(1,END=10017) (KBPOSOLD(J,ID,I),J=1, NBOCOLD(ID,I))
C             READ(1,END=10017) (IBANFOLD(J,ID,I),J=1, NBOCOLD(ID,I))
C             READ(1,END=10017) (JBANFOLD(J,ID,I),J=1, NBOCOLD(ID,I))
C             READ(1,END=10017) (KBANFOLD(J,ID,I),J=1, NBOCOLD(ID,I))
C             READ(1,END=10017) (IBENDOLD(J,ID,I),J=1, NBOCOLD(ID,I))
C             READ(1,END=10017) (JBENDOLD(J,ID,I),J=1, NBOCOLD(ID,I))
C             READ(1,END=10017) (KBENDOLD(J,ID,I),J=1, NBOCOLD(ID,I))
            ENDDO
         ELSE

            READ(1,END=10016) 
     $          FRONTOLD(1,I),BACKOLD(1,I),RIGHTOLD(1,I),
     $          LEFTOLD(1,I),BOTTOMOLD(1,I), TOPOLD(1,I), CUBEOLD(1,I)
             
         ENDIF

         READ(1,END=10023) XHOMOGOLD(I),YHOMOGOLD(I),ZHOMOGOLD(I)
         READ(1) LPLEVELOLD(I)
      ENDDO

      DO I=1,NBODOLD
         READ(1,END=10030) CTYPO(I)
         READ(1,END=10031)
     $        IB1O(I),IB2O(I),JB1O(I),JB2O(I),KB1O(I),KB2O(I)
         READ(1,END=10032) 
     $        XB1O(I),XB2O(I),YB1O(I),YB2O(I),ZB1O(I),ZB2O(I)
         READ(1,END=10033) 
     $        NCOUNO(I),XMITO(I),HEIGHTO(I),ALPHAO(I),CDIRO(I)
      ENDDO


      READ(1,END=10050)  (ISELEA(I),I=1,2*752)
      READ(1,END=10050)  (ISAMPA(I),I=1,752*NGRDOLD)
      READ(1,END=10060)  (ISLINA(N),N=1,NAUFOLD)

CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72

      ELSE
C                                 EINLESEN EINES MLET - ERGEBNISFILES
C
         WRITE (6,*) 
     &   'DIBHEAD DIBHEADDIBHEAD DIBHEADDIBHEAD DIBHEADDIBHEAD DIBHEAD'
         WRITE (6,*) 
     &   'DAS ERGEBNISFILE SCHEINT MIT MLET ERZEUGT ZU SEIN !!!'
         WRITE (6,*) 
     &   'DIBHEAD DIBHEADDIBHEAD DIBHEADDIBHEAD DIBHEADDIBHEAD DIBHEAD'

         NGRDOLD = 1
         NBODOLD = 0
         NAUFOLD = 0

         READ(1,END=10004)   KKO8,JJO8,IIO8

         KMXOLD(1) = KKO8
         JMXOLD(1) = JJO8
         IMXOLD(1) = IIO8


      ENDIF

 
      RETURN

CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C                                    FEHLERBEHANDLUNG

10000 STOP 'EOF BEIM BINAEREN EINLESEN VON CIDENT AUF KANAL 1'
10001 STOP 'EOF BEIM BINAEREN EINLESEN VON IIDENT AUF KANAL 1'
10002 STOP 'EOF BEIM BINAEREN EINLESEN VON RIDENT AUF KANAL 1'
10003 STOP 'EOF BEIM BINAEREN EINLESEN VON NGRDOLD,NAUFOLD AUF KANAL 1'
10004 STOP 'EOF BEIM BINAEREN EINLESEN VON IMXOLD AUF KANAL 1'
10005 STOP 'EOF BEIM BINAEREN EINLESEN VON JMXOLD AUF KANAL 1'
10006 STOP 'EOF BEIM BINAEREN EINLESEN VON KMXOLD AUF KANAL 1'
10007 STOP 'EOF BEIM BINAEREN EINLESEN VON LEVEL AUF KANAL 1'
10008 STOP 'EOF BEIM BINAEREN EINLESEN VON LCHILD AUF KANAL 1'
10009 STOP 'EOF BEIM BINAEREN EINLESEN VON IPARENT AUF KANAL 1'
10010 STOP 'EOF BEIM BINAEREN EINLESEN VON IPOSITION AUF KANAL 1'
10011 STOP 'EOF BEIM BINAEREN EINLESEN VON JPOSITION AUF KANAL 1'
10012 STOP 'EOF BEIM BINAEREN EINLESEN VON KPOSITION AUF KANAL 1'
10013 STOP 'EOF BEIM BINAEREN EINLESEN VON XTOT AUF KANAL 1'
10014 STOP 'EOF BEIM BINAEREN EINLESEN VON YTOT AUF KANAL 1'
10015 STOP 'EOF BEIM BINAEREN EINLESEN VON ZTOT AUF KANAL 1'
10016 STOP 'EOF BEIM BINAEREN EINLESEN VON FRONT AUF KANAL 1'
10017 STOP 'EOF BEIM BINAEREN EINLESEN DER NACHBARN AUF KANAL 1'
10018 STOP 'EOF BEIM BINAEREN EINLESEN VON RIGHT AUF KANAL 1'
10019 STOP 'EOF BEIM BINAEREN EINLESEN VON LEFT AUF KANAL 1'
10020 STOP 'EOF BEIM BINAEREN EINLESEN VON BOTTOM AUF KANAL 1'
10021 STOP 'EOF BEIM BINAEREN EINLESEN VON TOP AUF KANAL 1'
10022 STOP 'EOF BEIM BINAEREN EINLESEN VON CUBE AUF KANAL 1'
10023 STOP 'EOF BEIM BINAEREN EINLESEN VON XHOMOG AUF KANAL 1'
10024 STOP 'EOF BEIM BINAEREN EINLESEN VON YHOMOG AUF KANAL 1'
10025 STOP 'EOF BEIM BINAEREN EINLESEN VON ZHOMOG AUF KANAL 1'

10030 STOP 'EOF BEIM BINAEREN EINLESEN VON CTYP(IBODY) AUF KANAL 1'
10031 STOP 'EOF BEIM BINAEREN EINLESEN VON IB1..KB2 AUF KANAL 1'
10032 STOP 'EOF BEIM BINAEREN EINLESEN VON XB1..ZB2 AUF KANAL 1'
10033 STOP 'EOF BEIM BINAEREN EINLESEN VON NCOUN..ZDIR AUF KANAL 1'

10050 STOP 'EOF BEIM BINAEREN EINLESEN VON ISELEA AUF KANAL 1'
10060 STOP 'EOF BEIM BINAEREN EINLESEN VON ISLINA AUF KANAL 1'


      END
