










CCCCC        DEFINITIONEN FUER C-PREPROZESSOR
C            MASCHINE

C              MESSAGE PASSING INTERFACE

C            RAEUMLICHE DISKRETISIERUNG
C
***********************************************************************
C                       KOMPAKT-UPWIND in X-RICHTUNG (3-TER ORDNUNG) fuer
C                       die U-Komponente (V und W bleiben Kompakt 4ter ordnung)
C                       falls im Stroemungsfeld eine Koerper vorhanden ist
C
***********************************************************************
C                       KOMPAKTVERF. in XYZ-RICHTUNG (4-TER ORDNUNG)


**********************************************************************
C                      Preprocessing with ADM for 2nd Order Central
***********************************************************************
CCC                     Bei periodischen Randbedingungen in X-Richtung
CCC                     ist eine hoehere O
C
CCC                     Bei periodischen Randbedingungen in Y-Richtung
CCC                     ist eine hoehere Ordnung moeglich
C
CCC                     Bei periodischen Randbedingungen in Y-Richtung:
CCC                     Zentraldiff. 4-ter Ordnung (Parallelisieung moeglich)
C
***********************************************************************
C
C
C            INTERPOLATION AN GITTER-GRENZEN

C            BEHANDLUNG DER TOPAR-RANDBEDINGUNG

C            ZEITLICHE DISKRETISIERUNG

C            FEINSTRUKTURMODELL

C            NICHT-NEWTONSCHE SPANNUNGEN


C            TRANSPORT UND ORIENTIERUNG VON PARTIKELN


C            SCALAR HEAT/TEMPERATURE TRANSPORT
C            APROXIMATE DECONVOLUTION FOR SCALAR
C            TURBULENT PRANDTL NUMBER 
C            PLOT LOCAL SCALAR CONVECTION DIFFUSION EXTREMES 
C            ANALYZE AND PLOT NEAR WALL GRID RESLOLUTION 
C            WRITE SPECIAL 1D LINE FOR TMIX FOR SPECTRA AND PDF
C            SCALAR TIME ADVANCEMENT/DISCRETISATION METHOD

C            STROEMUNG NACH OBEN?


C            BEHANDLUNG DER FLUKTUATIONS-RANDBEDINGUNG

C            BEHANDLUNG VON PPHYS ALS QUELLTERM IN TSTLE2

C            POSITIONIERUNG DER EINSTROEMPROFILE

C           STATISTIK


C                 GEMISCHTES

C                GRDFMI WIRD NICHT VERWENDET, DAHER EINSPARUNG DER FELDER
C                IGRHF UND GRHF

C                VERGROESSERN DER KJI-RICHTUNG BEI FORTSETZUNGSLAUF ERLAUBT!

C                RAUSSCHREIBEN VON ZEITRECORDS

C                FUER KORRELATIONEN UND HAEFIGKEITSVERTEILUNGEN
       SUBROUTINE SETCOMGRID (IDIM3D,IDIM2D,IDIM1D,NBUF,NBND,IDIMA,
     $               IDIM1L,IDIM2L,IDIMF,IGRID,IDUMMY,ISUB,ISLPAR,NGSUB)

C*STARLET***************************************************************
C    S E T C O M G R I D     SETZEN DES COMMON-BLOCKES
C                            COMGRID  FUER EIN GITTER
C*STARLET***************************************************************
C
C PARAM: IDIM3D   : - MAXIMALE DIMENSIONIERUNG DER 3D-FELDER
C        IDIM2D   : - MAXIMALE DIMENSIONIERUNG DER 2D-FELDER
C        IDIM1D   : - MAXIMALE DIMENSIONIERUNG DER 1D-FELDER
C        IDIMA    : - MAXIMALE DIMENSIONIERUNG DER AUSWERTEFELDER
C        IDIM1L   : - MAXIMALE DIMENSIONIERUNG DER LINIENFELDER
C        IDIM2L   : - MAXIMALE DIMENSIONIERUNG DER LINIENFELDER
C        IGRID    : - GITTER, FUER DAS DIE GROESSEN GESETZT WERDEN
C        IDUMMY =0:    GITTER IST BERECHNUNGSGITTER MIT STATISTIK
C               =1:    GITTER IST NUR FUER DRUCKKORREKTUR (DUMMYGITTER)
C        ISUB     :    GITTER IST UNTERGITTER AUS GEBIETSZERLEGUNG
C        ISLPAR   : - NUMMER DES GESLICEDEN GITTERS, FALLS ISUB=1
C        NGSUB    : - WIEVIELTES UNTERGITTER VON ISLPAR
C
C
C VERS:   3. 4.93 (MM)  : ORIGINAL
C        17. 6.93 (MM)  : DUMMYGITTER EINGEFUEHRT
C        11. 2.94 (MM)  : UNTERGITTER AUS GEBIETSZERLEGUNG 
C                         BERUECKSICHTIGT
C
C        21.04.98 (AO)  : IPB3 EINGEFUEHRT ZUR BEREITSTELLUNG
C                         VON 2D*3 - FELDERN IM DYNAMISCHEN MODELL
C                         NACH GERMANO
C
C*STARLET***************************************************************
C

      INTEGER MAXGRIDS,MAXBOCONDS
      PARAMETER ( MAXGRIDS         =128 )
      PARAMETER ( MAXBOCONDS       = 10 )


      COMMON /COMGRID/
     &               NGRID,    NGRDOLD,   NGRDSET, NGRDDFD,
     &               NAUFP,    NAUFOLD,
     &                 KMX,  JMX,  IMX,
     &                 KMXA, JMXA, IMXA,
     &                IP3D, IP2D, IP1D, IPBB,IPB3, IPBU,
     &                NOF3D,NOF2D,NOF1D,NOFBB,NOFB3,NOFBU,
     &                IPA,   IP1L,  IP2L,
     &                NOFA,  NOF1L, NOF2L,  
     &                 IC1,  IC2,  JC1,  JC2,  KC1,  KC2

      INTEGER
     &         KMX(MAXGRIDS),     JMX(MAXGRIDS),       IMX(MAXGRIDS),
     &        KMXA(MAXGRIDS),    JMXA(MAXGRIDS),      IMXA(MAXGRIDS),
     &        IP3D(MAXGRIDS),    IP2D(MAXGRIDS),      IP1D(MAXGRIDS),
     &        IPBB(MAXGRIDS),    IPB3(MAXGRIDS),      IPBU(MAXGRIDS),
     &        NOF3D,   NOF2D,   NOF1D,    NOFBB,   NOFBU,
     &         IPA(MAXGRIDS),    IP1L(MAXGRIDS),      IP2L(MAXGRIDS),
     &         NOFA,   NOF1L,   NOF2L,    NAUFP,
     &         IC1(MAXGRIDS),     IC2(MAXGRIDS),
     &         JC1(MAXGRIDS),     JC2(MAXGRIDS),
     &         KC1(MAXGRIDS),     KC2(MAXGRIDS)
 

      
      COMMON /COGRDPRO/ LEVEL,LCHILD,XMIN,YMIN,ZMIN,XTOT,YTOT,ZTOT
      COMMON /COGRDPRO/ XHOMOG,YHOMOG,ZHOMOG,NXGRAE,NYGRAE,NZGRAE
      COMMON /COGRDPRO/ GRADPX,UBULKX,LTST,LVP,LSCAI,LPLEVEL,LPOISSONDIR
      COMMON /COGRDPRO/ LSLICE,NXSLICE,NYSLICE,NZSLICE,NVPGRIDS
      COMMON /COGRDPRO/ CONV1SANF,CONV1SEND,TRANSLES1,TRANSLES2
      COMMON /COGRDPRO/ GRADPXOLD

      INTEGER LEVEL(MAXGRIDS),NVPGRIDS(MAXGRIDS)
      INTEGER NXGRAE(MAXGRIDS),NYGRAE(MAXGRIDS),NZGRAE(MAXGRIDS)
      INTEGER NXSLICE(MAXGRIDS),NYSLICE(MAXGRIDS),NZSLICE(MAXGRIDS)

      REAL XTOT(MAXGRIDS),YTOT(MAXGRIDS),ZTOT(MAXGRIDS)
      REAL XMIN(MAXGRIDS),YMIN(MAXGRIDS),ZMIN(MAXGRIDS)
      REAL GRADPX(MAXGRIDS),UBULKX(MAXGRIDS)
      REAL CONV1SANF(MAXGRIDS),CONV1SEND(MAXGRIDS)
      REAL TRANSLES1(MAXGRIDS),TRANSLES2(MAXGRIDS),GRADPXOLD(MAXGRIDS)

      LOGICAL LCHILD(MAXGRIDS),LSLICE(MAXGRIDS),LPOISSONDIR(MAXGRIDS)
      LOGICAL XHOMOG(MAXGRIDS),YHOMOG(MAXGRIDS),ZHOMOG(MAXGRIDS)
      LOGICAL LTST(MAXGRIDS),LVP(MAXGRIDS),LSCAI(MAXGRIDS)
      LOGICAL LPLEVEL(MAXGRIDS)

      INTEGER MAXLVLMAX,MINLVLMIN,MAXGRDSOFLVL

      PARAMETER ( MAXLVLMAX = 4,  MINLVLMIN = -4 )
      PARAMETER ( MAXGRDSOFLVL =260)

      COMMON /COLEVEL/ MAXLEVEL,MINLEVEL
      COMMON /COLEVEL/ NOFLEVEL,IGRDOFLEVEL,NOFPSDIR,IGRDOFPSDIR
      COMMON /COLEVEL/ NOFVPIT ,IGRDOFVPIT ,NOFTST,  IGRDOFTST
      COMMON /COLEVEL/ NOFSLCED,IGRDOFSLCED,NOFSLICE,IGRDOFSLICE
      COMMON /COLEVEL/ NOFSCAI, IGRDOFSCAI,NGRIDPERLEVEL,NOFTHISGRID

      INTEGER MAXLEVEL,MINLEVEL

      INTEGER NOFLEVEL   (             MINLVLMIN:MAXLVLMAX)
      INTEGER IGRDOFLEVEL(MAXGRDSOFLVL,MINLVLMIN:MAXLVLMAX)
      INTEGER NOFVPIT    (             MINLVLMIN:MAXLVLMAX)
      INTEGER IGRDOFVPIT (MAXGRDSOFLVL,MINLVLMIN:MAXLVLMAX)
      INTEGER NOFTST     (             MINLVLMIN:MAXLVLMAX)
      INTEGER IGRDOFTST  (MAXGRDSOFLVL,MINLVLMIN:MAXLVLMAX)
      INTEGER NOFSCAI    (             MINLVLMIN:MAXLVLMAX)
      INTEGER IGRDOFSCAI (MAXGRDSOFLVL,MINLVLMIN:MAXLVLMAX)
      INTEGER NOFSLCED   (             MINLVLMIN:MAXLVLMAX)
      INTEGER IGRDOFSLCED(MAXGRDSOFLVL,MINLVLMIN:MAXLVLMAX)
      INTEGER NOFSLICE   (             MINLVLMIN:MAXLVLMAX)
      INTEGER IGRDOFSLICE(MAXGRDSOFLVL,MINLVLMIN:MAXLVLMAX)
      INTEGER NOFPSDIR   (             MINLVLMIN:MAXLVLMAX)
      INTEGER IGRDOFPSDIR(MAXGRDSOFLVL,MINLVLMIN:MAXLVLMAX)
      INTEGER NGRIDPERLEVEL    
      INTEGER NOFTHISGRID(MAXGRDSOFLVL)

      INTEGER MAXPROCS,NUMPROCS,MYID,IDIM_MG_BUFS,IDIM_MG_BIG
      PARAMETER (MAXPROCS = 64)
      PARAMETER ( IDIM_MG_BUFS=  9000000 , IDIM_MG_BIG= 19500000 )
      COMMON /COIDTHR/ NUMPROCS,MYID,IDPROCOFGRD
      COMMON /COIDTHR/ NVPOFPROC,IVPOFPROC,NTSOFPROC,ITSOFPROC
      COMMON /COIDTHR/ NSIOFPROC,ISIOFPROC
      INTEGER IDPROCOFGRD(MAXGRIDS)
      INTEGER IVPOFPROC  (MAXGRDSOFLVL,0:MAXPROCS)
      INTEGER NVPOFPROC  (             0:MAXPROCS,MINLVLMIN:MAXLVLMAX)
      INTEGER ITSOFPROC  (MAXGRDSOFLVL,0:MAXPROCS)
      INTEGER NTSOFPROC  (             0:MAXPROCS,MINLVLMIN:MAXLVLMAX)
      INTEGER ISIOFPROC  (MAXGRDSOFLVL,0:MAXPROCS)
      INTEGER NSIOFPROC  (             0:MAXPROCS,MINLVLMIN:MAXLVLMAX)
      COMMON /MG_BUFS/ SENDBUF,RECVBUF,BIGBUF
      REAL SENDBUF(IDIM_MG_BUFS),RECVBUF(IDIM_MG_BUFS)
      REAL BIGBUF(IDIM_MG_BIG)
C
CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
      INTEGER IDIM3D,IDIM2D,IDIM1D,NBUF,NBND,IDIMA,
     $               IDIM1L,IDIM2L,IDIMF,IGRID,IDUMMY,ISUB,ISLPAR,NGSUB
CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C                           UEBERPRUEFUNGEN

      IF (IGRID .GT. MAXGRIDS) CALL ERRR (  555 ,'SETCOMGRID')
C050696      IF (IGRID .NE. NGRDSET+1 ) CALL ERRR (  556 ,'SETCOMGRID')
      IF ( IDUMMY.NE.0 .AND. IDUMMY.NE.1 ) CALL ERRR (557,'SETCOMGRID')
      IF ( ISUB  .NE.0 .AND. ISUB  .NE.1 ) CALL ERRR (558,'SETCOMGRID')

C
CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C                       IMX, JMX, KMX WURDEN IN STRLES EINGELESEN
C
      IF (LSLICE(IGRID)) THEN
C
C                              GITTER WIRD GEBIETSZERLEGT
C                              SUB-GITTER LIEGEN AUF SELBEN
C                              SPEICHERPLATZ UND MUESSEN 
C                              BERUECKSICHTIGT WERDEN

       CALL CHKNSLICE (IMX(IGRID),NXSLICE(IGRID),NBND,NXSUB,IGRID,'X')
       CALL CHKNSLICE (JMX(IGRID),NYSLICE(IGRID),NBND,NYSUB,IGRID,'Y')
       CALL CHKNSLICE (KMX(IGRID),NZSLICE(IGRID),NBND,NZSUB,IGRID,'Z')

       NOFSUBGRIDS = NXSLICE(IGRID)*NYSLICE(IGRID)*NZSLICE(IGRID)

C                                GROESSE DER 2D UND 3D FELDER

       NSIZE3D = 0
C070696       NSIZE3D = NOFSUBGRIDS*
C070696     $          (NXSUB+2*NBND)*(NYSUB+2*NBND)*(NZSUB+2*NBND)

       NSIZE2D = 0
C070696       NSIZE2D = NOFSUBGRIDS*
C070696     $          (MAX((NXSUB+2*NBND)*(NYSUB+2*NBND),
C070696     $               (NXSUB+2*NBND)*(NZSUB+2*NBND),
C070696     $               (NYSUB+2*NBND)*(NZSUB+2*NBND)))

       II            = (NXSUB + 2*NBND) * NXSLICE(IGRID)
       JJ            = (NYSUB + 2*NBND) * NYSLICE(IGRID)
       KK            = (NZSUB + 2*NBND) * NZSLICE(IGRID)

      ELSE

C
C                                GROESSE DER 2D UND 3D FELDER
C
       II = IMX(IGRID) 
       JJ = JMX(IGRID) 
       KK = KMX(IGRID) 

          NSIZE3D = II*JJ*KK
          NSIZE2D = MAX( II*JJ , II*KK , JJ*KK )

      ENDIF

      IF ( MAX(II,JJ,KK).GT.IDIMF)   THEN
		  write (6,*) 'setcomgrid: igrid, KK..:',igrid,kk,jj,ii
		  CALL ERRR (538,'SETCOMGRID')
       ENDIF

C
CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C
C
C                                ANZAHL DER AKTUELLEN GITTER
C
C050696        NGRDSET = NGRDSET + 1
C
C                                GROESSE DER 1D  UND PUFFERFELDER
C
        NSIZE1D = MAX(II,JJ,KK)
        NSIZEBB = NSIZE2D*2
        NSIZEB3 = NSIZE2D*3
        NSIZEBU = NSIZE2D*NBUF

C


          IP3D(IGRID) =  NOF3D + 1
          IP2D(IGRID) =  NOF2D + 1
          IPBB(IGRID) =  NOFBB + 1
          IPB3(IGRID) =  NOFB3 + 1
          IPBU(IGRID) =  NOFBU + 1
C
C                               1D-FELDER ERHALTEN AUCH BEI UNTERGITTER
C                               AUS GEBIETSZERLEGUNG EIGENEN ADDRESSRAUM

        IP1D(IGRID) =  NOF1D + 1

C
C                             ANZAHL DER BELEGTEN WERTE IN
C                             1D, 2D 3D UND PUFFERFELDERN
C

C100696      IF ( ISUB .NE. 1 ) THEN
        NOF3D =  NOF3D + NSIZE3D
        NOF2D =  NOF2D + NSIZE2D
        NOFBB =  NOFBB + NSIZEBB
        NOFB3 =  NOFB3 + NSIZEB3
        NOFBU =  NOFBU + NSIZEBU
C100696      ENDIF

        NOF1D =  NOF1D + NSIZE1D

CMRGL          write (6,*) 'setcomgrid: igrid, nof3d, ip3:'
CMRGL     $             ,igrid, nof3d, IP3D(IGRID)
CMRGL          write (6,*) 'setcomgrid: idim3d:',idim3d
C
C                               REICHT PLATZ AUS ?????
C

      IF ( ISUB .NE. 1) THEN
        IF( NOF3D  .GT. IDIM3D ) THEN
          WRITE (6,*)'IGRID,NOF3D,IDIM3D: ',IGRID,NOF3D,IDIM3D
		  CALL ERRR (  568 ,'SETCOMGRID: IDIM3D ZU KLEIN ')
        ENDIF
        IF( NOF2D  .GT. IDIM2D ) THEN
          WRITE (6,*)'IGRID,NOF2D,IDIM2D: ',IGRID,NOF2D,IDIM2D
          CALL ERRR (  569 ,'SETCOMGRID')
        ENDIF
        IF( NOFBB  .GT. IDIM2D*2) THEN
          WRITE (6,*)'IGRID,NOFBB,2*IDIM2D: ',IGRID,NOFBB,2*IDIM2D
          CALL ERRR (  571 ,'SETCOMGRID')
        ENDIF
        IF( NOFB3  .GT. IDIM2D*3) THEN
          WRITE (6,*)'IGRID,NOFB3,3*IDIM2D: ',IGRID,NOFB3,3*IDIM2D
          CALL ERRR (  600 ,'SETCOMGRID')
        ENDIF
        IF( NOFBU  .GT. IDIM2D*NBUF ) THEN
          WRITE (6,*)'IGRID,NOFBU,IDIM2D*NBUF: ',IGRID,NOFBU,IDIM2D*NBUF
          CALL ERRR (  572 ,'SETCOMGRID')
        ENDIF
      ENDIF
        IF( NOF1D  .GT. IDIM1D ) THEN
          WRITE (6,*)'IGRID,NOF1D,IDIM1D: ',IGRID,NOF1D,IDIM1D
          CALL ERRR (  570 ,'SETCOMGRID')
        ENDIF

C
C
C                                  FALLS DUMMYGITTER, WIRD VERWALTUNG
C                                  FUER STATISTIK NICHT BELEGT

        IF ( IDUMMY.EQ.1 ) RETURN


CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C                          FUER AUSWERTEFELDER
C
C                                 DIMENSIONIERUNG DER FUER DIE AUSWER-
C                                 TUNG BENOETIGTEN FELDER

C
C                                 START- U. STOPINDIZES FUER DIE LINIEN-
C                                 MITTELUNG IN X- UND Y-RICHTUNG


      IF (XHOMOG(IGRID)) THEN

         IMXA   (IGRID)  = 1

      ELSE

         IMXA   (IGRID)  = IMX  (IGRID)

      ENDIF

      IF (YHOMOG(IGRID)) THEN

         JMXA   (IGRID)  = 1

      ELSE

         JMXA   (IGRID)  = JMX  (IGRID)

      ENDIF

      IF (ZHOMOG(IGRID)) THEN

         KMXA   (IGRID)  = 1

      ELSE

         KMXA   (IGRID)  = KMX  (IGRID)

      ENDIF

C
C                             ANZAHL DER WORTE IN EINEM AUSWERTEFELD
C
      IF (LSLICE(IGRID)) THEN
        NSIZEA = 0
        NSIZE1L= 0
        NSIZE2L= 0
      ELSE

             NSIZEA = IMXA(IGRID)*JMXA(IGRID)*KMXA(IGRID)
             NSIZE1L= NSIZE1D*NAUFP
             NSIZE2L= NSIZE1D*NAUFP*2
      ENDIF

C
C                             "POINTER" DER AUSWERTEFELDER
C

           IF ( ISUB .EQ. 1 ) THEN
             IPA (IGRID) =  (NGSUB-1)*NSIZEA + IPA(ISLPAR)
             IP1L(IGRID) =  (NGSUB-1)*NSIZE1L + IP1L(ISLPAR)
             IP2L(IGRID) =  (NGSUB-1)*NSIZE2L + IP2L(ISLPAR)
           ELSE
             IPA (IGRID) =  NOFA + 1
             IP1L(IGRID) =  NOF1L + 1
             IP2L(IGRID) =  NOF2L + 1
           ENDIF

C
C                             ANZAHL DER BELEGTEN WORTE
C
      IF ( ISUB .NE. 1) THEN

       NOFA  = NOFA  + NSIZEA
       NOF1L = NOF1L + NSIZE1L
       NOF2L = NOF2L + NSIZE2L

      ENDIF

C
C                            REICHT PLATZ AUS????
C
       IF (NOFA .GT.IDIMA)  THEN
          WRITE (6,*)'IGRID,NOFA,IDIMA: ',IGRID,NOFA,IDIMA
          CALL ERRR(580,' SETCOMGRID')
       ENDIF
          
CCCCCCC       IF (NOF1L.GT.IDIM1L) CALL ERRR(581,' SETCOMGRID')
CCCCCCC       IF (NOF2L.GT.IDIM2L) CALL ERRR(582,' SETCOMGRID')

CCCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC72
C

      RETURN
      END
